
// // Exception --> are the run time errors


// class Lesson44 {
//     public static void main(String[] args) {
//         // Try Catch StateMent
//         int i =0;
        
//         int j = 0;
//         int arr[] = new int[4];



//         // in an operation if there is achance to get exception that statement can be put inside a try block 
//         // if exception happen you can write remedy in catch block
//         try
//         {
//             j = 18 / i;
//             System.out.println(arr[0]);
//         }
//         catch (ArithmeticException e) 
//         {
//             System.out.println("Math Error");
//         }
//         catch (ArrayIndexOutOfBoundsException e)
//         {
//             System.out.println("Stay in your Limit");
//         }
//         catch (Exception e)
//         {
//             System.out.println("Some thing went wrong.."+ e);
//         }
//         System.out.println(j);

//         System.out.println("Bye");
//     }

// }